image: eu.gcr.io/savannah-emr/golang-ci-image:0.0.4

services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  GOOGLE_APPLICATION_CREDENTIALS: $CI_PROJECT_DIR/bewell-app-ci.json
  DOCKER_IMAGE_TAG: "eu.gcr.io/bewell-app/schema-registry:${CI_COMMIT_REF_SLUG}"
  GKE_ZONE: europe-west2-b
  GKE_PROJECT: bewell-app

build:
  image: "eu.gcr.io/savannah-emr/gcloud-docker-in-docker:0.0.1"
  stage: build
  only:
    - develop
  before_script:
    - /google-cloud-sdk/bin/gcloud auth activate-service-account --key-file $GCLOUD_PRODUCTION_SERVICE_ACCOUNT
    - /google-cloud-sdk/bin/gcloud config set project bewell-app
    - docker login -u _json_key --password-stdin https://eu.gcr.io < $GCLOUD_PRODUCTION_SERVICE_ACCOUNT
    - export CLOUDSDK_CORE_PROJECT=bewell-app
    - /google-cloud-sdk/bin/gcloud auth configure-docker
  script:
    - docker build --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN -f $CI_PROJECT_DIR/Dockerfile . -t ${DOCKER_IMAGE_TAG}
    - docker -- push ${DOCKER_IMAGE_TAG}
  tags:
    - healthcloud-multi

deploy_to_demo:
  image: devth/helm
  stage: deploy
  only:
    - develop
  before_script:
    - gcloud auth activate-service-account --key-file $GCLOUD_PRODUCTION_SERVICE_ACCOUNT
    - gcloud config set project ${GKE_PROJECT}
    - gcloud config set compute/zone ${GKE_ZONE}
    - gcloud container clusters get-credentials uat-node-environment --zone ${GKE_ZONE} --project ${GKE_PROJECT}
  script:
    - helm upgrade
      --install
      --namespace="demo-namespace"
      --set app.name="app-demo"
      --set app.namespace="demo-namespace"
      --set app.replicaCount=1
      --set app.container.env.assets_url="http://demo.schemaregistry.bewell.co.ke/"
      --set app.image="${DOCKER_IMAGE_TAG}"
      --set app.container.env.db_host="demo-mysql-service"
      --set app.service.name="demo-service"
      --set app.service.static_ip_name="demo-static-ip"
      --set app.service.namespace="demo-namespace"
      --set ingress.name="demo-ingress"
      --set ingress.namespace="demo-namespace"
      --set ingress.host="http://demo.schemaregistry.bewell.co.ke/"
      --set mysql.name="demo-mysql"
      --set mysql.service.name="demo-mysql-service"
      --set mysql.volume.pvc.name="demo-mysql-volume-claim"
      --set mysql.namespace="demo-namespace"
      --set mysql.service.namespace="demo-namespace"
      --set mysql.config.namespace="demo-namespace"
      --set mysql.volume.pvc.namespace="demo-namespace"
      --set redis.name="demo-redis-cluster"
      --set redis.namespace="demo-namespace"
      --wait
      demo-app-release
      ./deployment/k8s-chart
  tags:
    - healthcloud-multi

deploy_to_test:
  image: devth/helm
  stage: deploy
  only:
    - develop
  before_script:
    - gcloud auth activate-service-account --key-file $GCLOUD_PRODUCTION_SERVICE_ACCOUNT
    - gcloud config set project ${GKE_PROJECT}
    - gcloud config set compute/zone ${GKE_ZONE}
    - gcloud container clusters get-credentials uat-node-environment --zone ${GKE_ZONE} --project ${GKE_PROJECT}
  script:
    - helm upgrade
      --install
      --namespace="test-namespace"
      --set app.name="app-test"
      --set app.namespace="test-namespace"
      --set app.replicaCount=1
      --set app.container.env.assets_url="http://test.schemaregistry.bewell.co.ke/"
      --set app.image="${DOCKER_IMAGE_TAG}"
      --set app.container.env.db_host="test-mysql-service"
      --set app.service.name="test-service"
      --set app.service.static_ip_name="test-static-ip"
      --set app.service.namespace="test-namespace"
      --set ingress.name="test-ingress"
      --set ingress.namespace="test-namespace"
      --set ingress.host="http://test.schemaregistry.bewell.co.ke/"
      --set mysql.name="test-mysql"
      --set mysql.service.name="test-mysql-service"
      --set mysql.volume.pvc.name="test-mysql-volume-claim"
      --set mysql.namespace="test-namespace"
      --set mysql.service.namespace="test-namespace"
      --set mysql.config.namespace="test-namespace"
      --set mysql.volume.pvc.namespace="test-namespace"
      --set redis.name="test-redis-cluster"
      --set redis.namespace="test-namespace"
      --wait
      test-app-release
      ./deployment/k8s-chart
  tags:
    - healthcloud-multi

deploy_to_prod:
  image: devth/helm
  stage: deploy
  only:
    - master
  before_script:
    - gcloud auth activate-service-account --key-file $GCLOUD_PRODUCTION_SERVICE_ACCOUNT
    - gcloud config set project ${GKE_PROJECT}
    - gcloud config set compute/zone ${GKE_ZONE}
    - gcloud container clusters get-credentials uat-node-environment --zone ${GKE_ZONE} --project ${GKE_PROJECT}
  script:
    - helm upgrade
      --install
      --namespace="prod-namespace"
      --set app.name="app-prod"
      --set app.namespace="prod-namespace"
      --set app.replicaCount=1
      --set app.container.env.assets_url="http://schemaregistry.bewell.co.ke/"
      --set app.image="${DOCKER_IMAGE_TAG}"
      --set app.container.env.db_host="prod-mysql-service"
      --set app.service.name="prod-service"
      --set app.service.static_ip_name="prod-static-ip"
      --set app.service.namespace="prod-namespace"
      --set ingress.name="prod-ingress"
      --set ingress.namespace="prod-namespace"
      --set ingress.host="http://schemaregistry.bewell.co.ke/"
      --set mysql.name="prod-mysql"
      --set mysql.service.name="prod-mysql-service"
      --set mysql.volume.pvc.name="prod-mysql-volume-claim"
      --set mysql.namespace="prod-namespace"
      --set mysql.service.namespace="prod-namespace"
      --set mysql.config.namespace="prod-namespace"
      --set mysql.volume.pvc.namespace="prod-namespace"
      --set redis.name="prod-redis-cluster"
      --set redis.namespace="prod-namespace"
      --wait
      test-app-release
      ./deployment/k8s-chart
  tags:
    - healthcloud-multi
