image: eu.gcr.io/savannah-emr/golang-ci-image:0.0.4

services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  GOOGLE_APPLICATION_CREDENTIALS: $CI_PROJECT_DIR/bewell-app-ci.json
  DOCKER_IMAGE_TAG: "eu.gcr.io/bewell-app/schema-registry:${CI_COMMIT_REF_SLUG}"
  GKE_ZONE: europe-west2-b
  GKE_PROJECT: bewell-app

build:
  image: "eu.gcr.io/savannah-emr/gcloud-docker-in-docker:0.0.1"
  stage: build
  only:
    - develop
  before_script:
    - /google-cloud-sdk/bin/gcloud auth activate-service-account --key-file $GCLOUD_PRODUCTION_SERVICE_ACCOUNT
    - /google-cloud-sdk/bin/gcloud config set project bewell-app
    - docker login -u _json_key --password-stdin https://eu.gcr.io < $GCLOUD_PRODUCTION_SERVICE_ACCOUNT
    - export CLOUDSDK_CORE_PROJECT=bewell-app
    - /google-cloud-sdk/bin/gcloud auth configure-docker
  script:
    - docker build --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN -f $CI_PROJECT_DIR/Dockerfile . -t ${DOCKER_IMAGE_TAG}
    - docker -- push ${DOCKER_IMAGE_TAG}
  tags:
    - healthcloud-multi

deploy_to_demo:
  image: devth/helm
  stage: deploy
  only:
    - develop
  before_script:
    - gcloud auth activate-service-account --key-file $GCLOUD_PRODUCTION_SERVICE_ACCOUNT
    - gcloud config set project ${GKE_PROJECT}
    - gcloud config set compute/zone ${GKE_ZONE}
    - gcloud container clusters get-credentials schema-registry --zone ${GKE_ZONE} --project ${GKE_PROJECT}
  script:
    - helm upgrade
      --install
      --namespace="schemaregistry-demo-namespace"
      --set app.release_name="schemaregistry-demo-release"
      --set app.name="schemaregistry-demo-app"
      --set app.namespace="schemaregistry-demo-namespace"
      --set app.replicaCount=1
      --set app.container.env.assets_url="http://demo.schemaregistry.bewell.co.ke/"
      --set app.image="${DOCKER_IMAGE_TAG}"
      --set app.container.env.db_host="schemaregistry-demo-mysql-service"
      --set app.service.name="schemaregistry-demo-service"
      --set app.service.static_ip_name="schemaregistry-demo-static-ip"
      --set app.service.namespace="schemaregistry-demo-namespace"
      --set ingress.name="schemaregistry-demo-ingress"
      --set ingress.namespace="schemaregistry-demo-namespace"
      --set ingress.host="demo.schemaregistry.bewell.co.ke"
      --set ingress.annotations.class="gce"
      --set ingress.allow_http="false"
      --set app.certificate.name="schemaregistry-demo-certificate"
      --set mysql.name="demo-mysql"
      --set mysql.service.name="schemaregistry-demo-mysql-service"
      --set mysql.volume.pvc.name="schemaregistry-demo-mysql-volume-claim"
      --set mysql.namespace="schemaregistry-demo-namespace"
      --set mysql.service.namespace="schemaregistry-demo-namespace"
      --set mysql.config.namespace="schemaregistry-demo-namespace"
      --set mysql.volume.pvc.namespace="schemaregistry-demo-namespace"
      --set redis.name="schemaregistry-demo-redis-cluster"
      --set redis.namespace="schemaregistry-demo-namespace"
      --wait
      schemaregistry-demo-release
      ./deployment/k8s-chart
  tags:
    - healthcloud-multi

deploy_to_test:
  image: devth/helm
  stage: deploy
  only:
    - develop
  before_script:
    - gcloud auth activate-service-account --key-file $GCLOUD_PRODUCTION_SERVICE_ACCOUNT
    - gcloud config set project ${GKE_PROJECT}
    - gcloud config set compute/zone ${GKE_ZONE}
    - gcloud container clusters get-credentials schema-registry --zone ${GKE_ZONE} --project ${GKE_PROJECT}
  script:
    - helm upgrade
      --install
      --namespace="schemaregistry-test-namespace"
      --set app.release_name="schemaregistry-test-release"
      --set app.name="schemaregistry-test-app"
      --set app.namespace="schemaregistry-test-namespace"
      --set app.replicaCount=1
      --set app.container.env.assets_url="http://test.schemaregistry.bewell.co.ke/"
      --set app.image="${DOCKER_IMAGE_TAG}"
      --set app.container.env.db_host="schemaregistry-test-mysql-service"
      --set app.service.name="schemaregistry-test-service"
      --set app.service.static_ip_name="schemaregistry-test-static-ip"
      --set app.service.namespace="schemaregistry-test-namespace"
      --set ingress.name="schemaregistry-test-ingress"
      --set ingress.namespace="schemaregistry-test-namespace"
      --set ingress.host="test.schemaregistry.bewell.co.ke"
      --set ingress.annotations.class="gce"
      --set ingress.allow_http="false"
      --set app.certificate.name="schemaregistry-test-certificate"
      --set mysql.name="schemaregistry-test-mysql"
      --set mysql.service.name="schemaregistry-test-mysql-service"
      --set mysql.volume.pvc.name="schemaregistry-test-mysql-volume-claim"
      --set mysql.namespace="schemaregistry-test-namespace"
      --set mysql.service.namespace="schemaregistry-test-namespace"
      --set mysql.config.namespace="schemaregistry-test-namespace"
      --set mysql.volume.pvc.namespace="schemaregistry-test-namespace"
      --set redis.name="schemaregistry-test-redis-cluster"
      --set redis.namespace="schemaregistry-test-namespace"
      --wait
      schemaregistry-test-release
      ./deployment/k8s-chart
  tags:
    - healthcloud-multi

deploy_to_prod:
  image: devth/helm
  stage: deploy
  only:
    - master
  before_script:
    - gcloud auth activate-service-account --key-file $GCLOUD_PRODUCTION_SERVICE_ACCOUNT
    - gcloud config set project ${GKE_PROJECT}
    - gcloud config set compute/zone ${GKE_ZONE}
    - gcloud container clusters get-credentials schema-registry --zone ${GKE_ZONE} --project ${GKE_PROJECT}
  script:
    - helm upgrade
      --install
      --namespace="schemaregistry-prod-namespace"
      --set app.release_name="schemaregistry-prod-release"
      --set app.name="schemaregistry-app-prod"
      --set app.namespace="schemaregistry-prod-namespace"
      --set app.replicaCount=1
      --set app.container.env.assets_url="http://schemaregistry.bewell.co.ke/"
      --set app.image="${DOCKER_IMAGE_TAG}"
      --set app.container.env.db_host="schemaregistry-prod-mysql-service"
      --set app.service.name="schemaregistry-prod-service"
      --set app.service.static_ip_name="schemaregistry-prod-static-ip"
      --set app.service.namespace="schemaregistry-prod-namespace"
      --set ingress.name="schemaregistry-prod-ingress"
      --set ingress.namespace="schemaregistry-prod-namespace"
      --set ingress.host="schemaregistry.bewell.co.ke"
      --set ingress.annotations.class="gce"
      --set ingress.allow_http="false"
      --set app.certificate.name="schemaregistry-prod-certificate"
      --set mysql.name="schemaregistry-prod-mysql"
      --set mysql.service.name="schemaregistry-prod-mysql-service"
      --set mysql.volume.pvc.name="schemaregistry-prod-mysql-volume-claim"
      --set mysql.namespace="schemaregistry-prod-namespace"
      --set mysql.service.namespace="schemaregistry-prod-namespace"
      --set mysql.config.namespace="schemaregistry-prod-namespace"
      --set mysql.volume.pvc.namespace="schemaregistry-prod-namespace"
      --set redis.name="schemaregistry-prod-redis-cluster"
      --set redis.namespace="schemaregistry-prod-namespace"
      --wait
      schemaregistry-prod-release
      ./deployment/k8s-chart
  tags:
    - healthcloud-multi
