app:
    group: backend
    container:
        port: 3000
        env:
            node_env: production
            port: 3000
            db_schema: gql-schema-registry-db

    service:
        type: NodePort
        port: 3000

ingress:
    annotations:
        class: gce
    paths:
        - /*
        - /assets/management-ui-standalone.css
        - /assets/management-ui-standalone.js

mysql:
    name: mysql
    replicaCount: 1
    group: db
    container:
        image: "mysql:latest"
        port: 3306
    service:
        type: ClusterIP
        port: 3306
    volume:
        name: mysql-volume-mount
        kind: PersistentVolumeClaim
        mountPath: /var/lib/mysql
        pvc:
            accessMode: ReadWriteOnce
            storage: 10Gi
    config:
        name: mysql-config

        data:
            - key: MYSQL_DATABASE
              value: schema_registry
            - key: SERVICE_3306_NAME
              value: mysql-service

mysqlRootPassword: cm9vdA==

redis:
    container:
        image: "redis:6-alpine"
        port: 6379
        targetPort: 16379
    volume:
        name: conf
        pvc:
            defaultMode: 0755
            storage: 1Gi
