{{- $serviceName := .Values.app.service.name -}}
{{- $servicePort := .Values.app.service.port -}}
{{- $paths := .Values.ingress.paths -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.ingress.namespace }}
  annotations:
        kubernetes.io/ingress.global-static-ip-name: {{ .Values.app.service.static_ip_name }}
        networking.gke.io/managed-certificates: {{ .Values.app.certificate.name }}
        kubernetes.io/ingress.class: {{ .Values.ingress.annotations.class | quote }}
        kubernetes.io/ingress.allow-http: {{ .Values.ingress.allow_http | quote }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        {{- range $p := $paths }}
          - path: {{ $p }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
        {{- end }}

