apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.app.service.name }}
    namespace: {{ .Values.app.service.namespace }}
    labels:
        group: {{ .Values.app.group }}
spec:
    type: {{ .Values.app.service.type }}
    selector:
        app: {{ .Values.app.name }}
    ports:
        - port: {{ .Values.app.service.port }}
          targetPort: {{ .Values.app.container.port }}
