apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.mysql.service.name }}
    namespace: {{ .Values.mysql.service.namespace }}
    labels:
        group: {{ .Values.mysql.group }}
spec:
    type: {{ .Values.mysql.service.type }}
    selector:
        app: {{ .Values.mysql.name }}
    ports:
        - port: {{ .Values.mysql.service.port }}
          targetPort: {{ .Values.mysql.container.port }}
