apiVersion: v1
kind: {{ .Values.mysql.volume.kind }}
metadata:
    name: {{ .Values.mysql.volume.pvc.name }}
    namespace: {{ .Values.mysql.volume.pvc.namespace }}
spec:
    accessModes:
        - {{ .Values.mysql.volume.pvc.accessMode }}
    resources:
        requests:
            storage: {{ .Values.mysql.volume.pvc.storage }}
