apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.mysql.name }}
    namespace: {{ .Values.mysql.namespace }}
    labels:
        app: {{ .Values.mysql.name }}
        group: {{ .Values.mysql.group }}
spec:
    replicas: {{ .Values.mysql.replicaCount }}
    selector:
        matchLabels:
            app: {{ .Values.mysql.name }}
    template:
        metadata:
            labels:
                app: {{ .Values.mysql.name }}
                group: {{ .Values.mysql.group }}
        spec:
            volumes:
                - name: {{ .Values.mysql.volume.name }}
                  persistentVolumeClaim:
                      claimName: {{ .Values.mysql.volume.pvc.name }}
            containers:
                - name: {{ .Values.mysql.name }}
                  image: {{ .Values.mysql.container.image }}
                  ports:
                      - containerPort: {{ .Values.mysql.container.port }}
                  envFrom:
                      - configMapRef:
                            name: {{ .Values.mysql.config.name }}
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: {{ template "mysql.secretName" . }}
                                key: mysql-root-password
                  volumeMounts:
                      - name: {{ .Values.mysql.volume.name }}
                        mountPath: {{ .Values.mysql.volume.mountPath }}
